Hi there!
This is the code template for CW2 task2 of COMP34711 2025/26.

- <span style="color:red; font-size:1em">First of all, please rename the notebook into "{your_student_id}_CW2_task{your_task_number}.ipynb", for example "12345678_CW2_task2.ipynb".</span>

- In this template, we only provide the minimal structure for your coursework.
  
- Please carefully read and organize your code in the template we provided.

## Constants

In [143]:
#Please keep only necessary information in this cell.

#----------------------Please keep all following constants unchanged.----------------------------------------
NUM_ROWS_VALIDATION = 1031 # Number of rows in validation set
NUM_ROWS_TEST = 1053 # Number of rows in test set

#----------------------Please modify the following constants to fit your actual value.-----------------------
STUDENT_ID = '11445473'  # Replace with your actual 8-digits student ID
TRAINING_SET = './data/CW2_training_dataset.csv' # Replace with the actual path to your training dataset csv file
VALIDATION_SET = './data/CW2_validation_dataset.csv'  # Replace with the actual path to your validation dataset csv file
VALIDATION_SET_OUTPUT = f'./data/{STUDENT_ID}_CW2_task2_validation_results.csv'  # Replace with the actual path to your validation prediction csv file
TEST_SET_INPUT = './data/CW2_test_dataset.csv'  # Replace with the actual path to your test prediction csv file

#----------------------Your constants------------------------------------------------
# By adding more constants here, you can help improve the clarity and maintainability of your code and make the reviewing easier for TAs.
MODEL_NAME = "roberta-base"
NUM_LABELS = 8
MAX_LEN = 256
BATCH_SIZE = 16
LR = 2e-5
EPOCHS = 3
MAX_SYNOPSIS_LENGTH = 5000
HIDDEN_DIM = 64

## Installations

In [144]:
# Install required packages for the coursework
# Uncomment and run the following lines if needed

# !pip install pandas scikit-learn --quiet
# !pip install transformers datasets torch

## Imports

In [145]:
#Please keep all imports of your code cells in this cell

#---------------------Required imports----------------------
import pandas as pd
import re
import sys
import os.path
import csv
from sklearn.metrics import f1_score
#----------------------Your imports-------------------------
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizer, RobertaModel
import numpy as np

## Start of your code cells

- The code cells provided below are demo code format for TAs to quickly locate your implementation.

- You have full right to freely add/delete/edit the titles and codes in the following cells.

- Please follow this genre order: "comedy, cult, flashback, historical, revenge, romantic, scifi, violence".

### Model Loading

In [146]:
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
roberta_model = RobertaModel.from_pretrained("roberta-base")

# Freeze it - don't retrain
for param in roberta_model.parameters():
    param.requires_grad = False

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


### Data Loading

In [147]:
#this makes sure to use the gpu if available otherwise the cpu
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Your code cells here
df = pd.read_csv(TRAINING_SET)

GENRE_COLS = [
    "comedy", "cult", "flashback", "historical",
    "revenge", "romantic", "scifi", "violence"
]

# extract Y from training df
Y_train = df[GENRE_COLS].values   # shape (7127, 8)

# Count positives and negatives per label
pos_counts = Y_train.sum(axis=0)
neg_counts = (Y_train.shape[0] - pos_counts)

# Compute pos_weight = neg/pos
pos_weight = torch.tensor(neg_counts / pos_counts, dtype=torch.float32).to(device)

print(pos_weight)


tensor([ 4.7943,  2.9572,  2.5724, 36.3141,  3.2423,  2.5760, 33.4300,  1.3506],
       device='cuda:0')


### Tokenization

In [148]:
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
tokenizer.padding_side = "right"
tokenizer.truncation_side = "right"
model = RobertaModel.from_pretrained('roberta-base')


Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [149]:
class MovieDataset(Dataset):
    def __init__(self, df, tokenizer):
        self.df = df
        self.tokenizer = tokenizer
        self.genre_cols = [
            "comedy", "cult", "flashback", "historical",
            "revenge", "romantic", "scifi", "violence"
        ]

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        text = f"{row.title} [SEP] {row.plot_synopsis}"

        # Tokenize directly with max_length=512
        enc = self.tokenizer(
            text,
            max_length=512,         # roberta-base max tokens
            truncation=True,
            padding='max_length',
            return_tensors='pt'
        )

        labels = torch.tensor(row[self.genre_cols].values.astype(float), dtype=torch.float)

        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels": labels
        }


### Model and Training

In [150]:
import torch
import torch.nn as nn
from transformers import RobertaModel

class RobertaBiLSTMClassifier(nn.Module):
    def __init__(self, hidden_dim=256, num_labels=8, roberta_model_name="roberta-base", pos_weight=None):
        super().__init__()

        # Pretrained RoBERTa
        self.roberta = RobertaModel.from_pretrained(roberta_model_name)

        for param in self.roberta.parameters():
            param.requires_grad = False

        # BiLSTM on top of RoBERTa embeddings
        self.lstm = nn.LSTM(
            input_size=768,       # RoBERTa hidden size
            hidden_size=hidden_dim,
            num_layers=1,
            bidirectional=True,
            batch_first=True
        )

        # Classifier
        self.fc = nn.Linear(2 * hidden_dim, num_labels)
        
        # Store pos_weight as a buffer (automatically moves to device with model)
        if pos_weight is not None:
            self.register_buffer('pos_weight', pos_weight)
        else:
            self.pos_weight = None

    def forward(self, input_ids, attention_mask, labels=None):
        # RoBERTa embeddings
        outputs = self.roberta(input_ids=input_ids, attention_mask=attention_mask)
        embeddings = outputs.last_hidden_state  # [batch, seq_len, 768]

        lengths = attention_mask.sum(dim=1).cpu()

        packed = nn.utils.rnn.pack_padded_sequence(
            embeddings, 
            lengths,
            batch_first=True,
            enforce_sorted=False
        )

        packed_out, (h_n, c_n) = self.lstm(packed)
        h_forward = h_n[0]    # forward direction
        h_backward = h_n[1]   # backward direction
        h_final = torch.cat([h_forward, h_backward], dim=1)

        # Classifier
        logits = self.fc(h_final)
        
        if labels is not None:
            loss_fn = nn.BCEWithLogitsLoss(pos_weight=self.pos_weight)
            loss = loss_fn(logits, labels)
            return loss, logits
        
        return logits

In [151]:
dataset = MovieDataset(df, tokenizer)

loader = DataLoader(
    dataset,
    batch_size= BATCH_SIZE,
    shuffle=True
)


In [152]:
EPOCHS = 10
model = RobertaBiLSTMClassifier(hidden_dim=HIDDEN_DIM, pos_weight=pos_weight).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=2e-5)

# Load test set
validation_df_raw = pd.read_csv(VALIDATION_SET)

X_validation = MovieDataset(validation_df_raw, tokenizer)
validation_loader = DataLoader(X_validation, batch_size= BATCH_SIZE, shuffle=False)

print(device)

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    
    for i, batch in enumerate(loader):

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        optimizer.zero_grad()
        loss, logits = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss.backward()
        optimizer.step()

        if i % 50 == 0:  # Every 50 batches
            with torch.no_grad():
                probs = torch.sigmoid(logits)
                print(f"  Batch {i}: Probs - min={probs.min():.3f}, max={probs.max():.3f}, mean={probs.mean():.3f}")

        total_loss += loss.item() * input_ids.size(0)

    avg_loss = total_loss / len(loader.dataset)
    print(f"Epoch {epoch+1}/{EPOCHS}, Loss = {avg_loss:.4f}")

    # Validate after each epoch
    model.eval()
    val_probs = []
    with torch.no_grad():
        for batch in validation_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            logits = model(input_ids=input_ids, attention_mask=attention_mask)
            probs = torch.sigmoid(logits)
            val_probs.append(probs)


Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


cuda
  Batch 0: Probs - min=0.447, max=0.612, mean=0.516
  Batch 50: Probs - min=0.446, max=0.616, mean=0.511
  Batch 100: Probs - min=0.442, max=0.610, mean=0.513
  Batch 150: Probs - min=0.446, max=0.605, mean=0.510
  Batch 200: Probs - min=0.455, max=0.586, mean=0.509
  Batch 250: Probs - min=0.453, max=0.587, mean=0.507
  Batch 300: Probs - min=0.450, max=0.560, mean=0.507
  Batch 350: Probs - min=0.447, max=0.576, mean=0.507
  Batch 400: Probs - min=0.469, max=0.567, mean=0.508
Epoch 1/10, Loss = 1.0928
  Batch 0: Probs - min=0.455, max=0.562, mean=0.506
  Batch 50: Probs - min=0.466, max=0.548, mean=0.507
  Batch 100: Probs - min=0.473, max=0.549, mean=0.507
  Batch 150: Probs - min=0.466, max=0.545, mean=0.508
  Batch 200: Probs - min=0.477, max=0.539, mean=0.506
  Batch 250: Probs - min=0.467, max=0.542, mean=0.506
  Batch 300: Probs - min=0.462, max=0.554, mean=0.504
  Batch 350: Probs - min=0.471, max=0.552, mean=0.504
  Batch 400: Probs - min=0.460, max=0.543, mean=0.504
Epo

In [153]:
torch.save(model.state_dict(), "bilstm_genre_model_task2.pt")

### Finding the best thresholds

In [154]:
# Load test set
validation_df_raw = pd.read_csv(VALIDATION_SET)

X_validation = MovieDataset(validation_df_raw, tokenizer)
validation_loader = DataLoader(X_validation, batch_size= BATCH_SIZE, shuffle=False)

model.eval()
all_probs = []
all_labels = []

with torch.no_grad():
    for batch in validation_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        loss, logits = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        probs = torch.sigmoid(logits).cpu()

        all_probs.append(probs)
        all_labels.append(labels.cpu())

probs_val = torch.cat(all_probs, dim=0).numpy()
y_val = torch.cat(all_labels, dim=0).cpu().numpy()

In [155]:
print(probs_val[10])
print(y_val[10])

[0.4797608  0.38017586 0.56683415 0.4137713  0.48122752 0.6662515
 0.1957885  0.38954678]
[0. 0. 1. 0. 1. 0. 0. 1.]


In [156]:
def find_best_thresholds(probs, y_true):
    thresholds = np.linspace(0, 1, 101)  # 0.00 → 1.00
    best_thresholds = []

    for col in range(probs.shape[1]):   # for each genre
        best_f1 = 0
        best_thr = 0.5

        for thr in thresholds:
            preds = (probs[:, col] >= thr).astype(int)
            f1 = f1_score(y_true[:, col], preds, zero_division=0)

            if f1 > best_f1:
                best_f1 = f1
                best_thr = thr

        best_thresholds.append(best_thr)

    return np.array(best_thresholds)

best_thresholds = find_best_thresholds(probs_val, y_val)
print("BEST THRESHOLDS PER GENRE:")
print(best_thresholds)

BEST THRESHOLDS PER GENRE:
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]


In [157]:
#best_thresholds = np.array([0.46, 0.38, 0.34, 0.79, 0.42, 0.55, 0.93, 0.34])

### Prediction

In [158]:

word_to_vec = {}

model.eval()

def predict_dataframe(df, model, tokenizer, batch_size=BATCH_SIZE, device="cuda"):
    dataset = MovieDataset(df, tokenizer)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    all_preds = []

    model.to(device)
    model.eval()
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            logits = model(input_ids=input_ids, attention_mask=attention_mask)
            probs = torch.sigmoid(logits)

            # If you have per-label thresholds
            print(best_thresholds)
            thresholds_tensor = torch.tensor(best_thresholds, device=probs.device, dtype=probs.dtype)
            preds = (probs >= thresholds_tensor).int()

            all_preds.append(preds.cpu())

    all_preds = torch.cat(all_preds, dim=0).numpy()
    return all_preds  # shape: (len(df), 8)


## End of your code cells

### Evaluation scripts

In [159]:
def read_data(submission_file_path, gold_standard_file_path):
    """
    Read submission and gold standard files.
    Extract student ID from filename.
    """
    # Try to find student ID from the filename (looks for 8 digit numbers)
    id_regex = r'\d{8}'

    user_id = re.findall(id_regex, submission_file_path)
    print("Found your ID: ", user_id)
    if user_id:
        user_id = user_id[0]
    else:
        user_id = 'Unknown'

    # Load submission CSV
    print(f"\nLoading submission file: {submission_file_path}")
    submission_df = pd.read_csv(submission_file_path, sep=',', header=None,
                                quoting=csv.QUOTE_NONE, encoding='utf-8')

    # Load gold standard CSV
    print(f"Loading gold standard file: {gold_standard_file_path}")
    gold_standard_df = pd.read_csv(gold_standard_file_path, header=None)

    # Remove columns 1 and 2 (keep only ID and labels)
    gold_standard_df = gold_standard_df.drop([1, 2], axis=1)
    # Skip header row
    gold_standard_df = gold_standard_df.iloc[1:]

    return submission_df, gold_standard_df, user_id


def match_and_prepare_data(submission_df, gold_standard_df, user_id):
    """
    Match submission rows with gold standard rows by ID.
    Prepare data for evaluation.
    """
    gold_standard_labels = []
    submission_labels = []
    missed_rows = []
    submission_df_copy = submission_df.copy()

    print(f"\nMatching submission with gold standard...")
    print(f"Gold standard rows: {len(gold_standard_df)}")
    print(f"Submission rows: {len(submission_df_copy)}")

    # Match each gold standard row with submission
    for index, row in gold_standard_df.iterrows():
        row = row.reset_index(drop=True)
        row_found = False
        row_id = row[0]

        # Extract gold standard labels
        row_labels = [int(row[i]) for i in range(1, len(row))]
        gold_standard_labels.append(row_labels)

        # Find corresponding submission row
        for sub_index, submission_row in submission_df_copy.iterrows():
            if submission_row[0].strip() == row_id.strip():
                try:
                    # Extract submission labels
                    submission_row_labels = [int(submission_row[i]) for i in range(1, len(submission_row))]
                except:
                    # Handle malformed labels (take first character if multi-digit)
                    submission_row_labels = [int(str(submission_row[i])[0]) for i in range(1, len(submission_row))]

                submission_labels.append(submission_row_labels)
                row_found = True
                submission_df_copy.drop(sub_index, inplace=True)
                break

        if not row_found:
            # If row is missing, add inverse labels (worst possible prediction)
            missed_rows.append(row_id)
            submission_labels.append([0 if label == 1 else 1 for label in row_labels])

    return gold_standard_labels, submission_labels, missed_rows


def evaluate_submission(gold_standard_labels, submission_labels):
    """
    Calculate weighted F1 score.
    """
    print(f"\nCalculating weighted F1 score...")

    # Calculate weighted F1 score (accounts for class imbalance)
    f1_weighted = f1_score(gold_standard_labels, submission_labels, average='weighted')

    return f1_weighted


def print_results(user_id, f1_weighted, missed_rows):
    """
    Print evaluation results to screen.
    """
    print("\n" + "="*70)
    print("YOUR SUBMISSION EVALUATION REPORT")
    print("="*70)

    # Alert if ID not found in filename
    if user_id == 'Unknown':
        print('WARNING: ID not found in filename!')
        print('   Please ensure your filename contains your 8-digit student ID.')
        print()

    print(f"Your ID: {user_id}")
    print()

    # Display F1 score with visual indicator
    print("EVALUATION RESULTS:")
    print(f"   Weighted F1 Score: {f1_weighted:.4f}")
    print()

    # Report missing rows
    if missed_rows:
        print(f"MISSING DATA ({len(missed_rows)} rows not found):")
        print("-" * 70)
        for i, row in enumerate(missed_rows[:10], 1):  # Show first 10
            print(f"    {i}. Row ID: {row}")
        if len(missed_rows) > 10:
            print(f"    ... and {len(missed_rows) - 10} more missing rows")
        print()
        print("TIP: Make sure your submission includes all required rows.")
        print("        Missing rows are penalized with worst possible predictions.")
    else:
        print("DATA COMPLETENESS: All expected rows found in your submission!")

    print()
    print("="*70)
    print()


def evaluate(submission_path, gold_standard_path):
    """
    Main function to run the submission evaluation script.
    """

    submission_file = submission_path
    gold_standard_file = gold_standard_path

    # Check if files exist
    if not os.path.exists(submission_file):
        print(f"Error: Your submission file '{submission_file}' not found!")
        print("Make sure the file path is correct and the file exists.")
        sys.exit(1)

    if not os.path.exists(gold_standard_file):
        print(f"Error: Gold standard file '{gold_standard_file}' not found!")
        print("Make sure you have the correct gold standard file.")
        sys.exit(1)

    try:
        # Step 1: Read data
        submission_df, gold_standard_df, user_id = read_data(submission_file, gold_standard_file)

        # Step 2: Match and prepare data
        gold_standard_labels, submission_labels, missed_rows = match_and_prepare_data(
            submission_df, gold_standard_df, user_id
        )

        # Step 3: Evaluate
        f1_weighted = evaluate_submission(gold_standard_labels, submission_labels)

        # Step 4: Print results
        print_results(user_id, f1_weighted, missed_rows)

    except Exception as e:
        print(f"Error during evaluation: {str(e)}")
        print("Please check that your files are in the correct CSV format.")
        print("Each row should contain: ID, label1, label2, label3, ...")
        import traceback
        traceback.print_exc()
        sys.exit(1)

### Evaluate the model on the validation dataset

In [163]:
# Please run the evaluation scripts cell above before running the mark_and_record

# Please make sure that output format is like following (no header row, no tilte and plot columns):
# 94834c61-0e30-4799-9998-6f74f6sbb204	0	1	0	0	1	0	0	0
# 559sdd28-b6a2-4662-ab55-a6678as26a56	0	0	0	0	0	0	1	0
# b71y3317-04cd-42f5-a380-d21dfasdbd36	0	0	0	0	1	0	0	0

evaluation_results = evaluate(VALIDATION_SET_OUTPUT, VALIDATION_SET)

Found your ID:  ['11445473']

Loading submission file: ./data/11445473_CW2_task2_validation_results.csv
Loading gold standard file: ./data/CW2_validation_dataset.csv

Matching submission with gold standard...
Gold standard rows: 1031
Submission rows: 1031

Calculating weighted F1 score...

YOUR SUBMISSION EVALUATION REPORT
Your ID: 11445473

EVALUATION RESULTS:
   Weighted F1 Score: 0.5006

DATA COMPLETENESS: All expected rows found in your submission!




### Save predictions to formatted file.

In [161]:
for i in best_thresholds:
    print(i)
    

0.52
0.41000000000000003
0.43
0.68
0.46
0.51
0.73
0.37


In [162]:
# Now please modify the code to format your output csv file.

# Please make sure that output format is like following (no header row, no tilte and plot columns):
# 94834c61-0e30-4799-9998-6f74f6sbb204	0	1	0	0	1	0	0	0
# 559sdd28-b6a2-4662-ab55-a6678as26a56	0	0	0	0	0	0	1	0
# b71y3317-04cd-42f5-a380-d21dfasdbd36	0	0	0	0	1	0	0	0

test_df = pd.read_csv(VALIDATION_SET)
test_preds = predict_dataframe(test_df, model, tokenizer)

output_df = pd.DataFrame(test_preds, columns=GENRE_COLS)
output_df.insert(0, 'ID', test_df['ID'])

# For example, if you have a DataFrame named 'output_df', you can save it
#assert isinstance(output_df, pd.DataFrame)
#assert len(output_df) == NUM_ROWS_TEST, "Output length is not aligned with the testdata.csv."
#assert len(output_df.columns) == 9, "Please make sure to follow the format above and keep only IDs and 8 columns of prediction."
output_df.to_csv(f'./data/{STUDENT_ID}_CW2_task2_validation_results.csv', index=False, header=False)

[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.73 0.37]
[0.52 0.41 0.43 0.68 0.46 0.51 0.7